# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVciP1BNCY8lW42UGc4ioMVg8m3IQwPk

MESSAGE SPAM DETECTION USING DEEP LEARNING
"""

import tensorflow as tf
print(tf.__version__)

# Commented out IPython magic to ensure Python compatibility.
# import libraries for reading data, exploring and plotting
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
# %matplotlib inline
# library for train test split
from sklearn.model_selection import train_test_split
# deep learning libraries for text pre-processing
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
# Modeling
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense, Dropout, LSTM, Bidirectional

url = 'https://raw.githubusercontent.com/Yakin1001/project/master/SMSSpamCollection'
messages = pd.read_csv(url, sep ='\t',names=["label", "message"])
messages[:3]

"""The describe() method from pandas provide a summary statistics. Such as, there are 5,572 labels and messages. There are two unique labels indicating for “ham” and “spam”. We can also observe that there are less unique messages (5,169) than total message count(5,572) indicating some repeated messages. The top label is “ham” and the top message in the data is “Sorry, I’ll call later”."""

messages.describe()

duplicatedRow = messages[messages.duplicated()]
print(duplicatedRow[:5])

"""There are 4,825 ham compared to 747 spam messages.The most popular ham message is “Sorry, I’ll call later”, whereas the most popular spam message is “Please call our customer service…” which occurred 30 and 4 times, respectively.

"""

messages.groupby('label').describe().T

"""We further explore the data by label groups by creating a WordCloud and a bar chart.

To visualize using WordCloud(), we extract words most commonly found in ham and spam messages, remove meaningless stop words such as “the”, “a” , “is” etc, and plot it. The WordCloud visualizes the most frequent words in the given text.

The ham message WordCloud below shows that “now”, “work”, “How”, “Ok” and “Sorry” are the most commonly appeared word in ham messages.
"""

# Get all the ham and spam message
ham_msg = messages[messages.label =='ham']
spam_msg = messages[messages.label=='spam']
# Create numpy list to visualize using wordcloud
ham_msg_text = " ".join(ham_msg.message.to_numpy().tolist())
spam_msg_text = " ".join(spam_msg.message.to_numpy().tolist())

# wordcloud of ham messages
ham_msg_cloud = WordCloud(width =520, height =260, stopwords=STOPWORDS,max_font_size=50, background_color ="black", colormap='Blues').generate(ham_msg_text)
plt.figure(figsize=(16,10))
plt.imshow(ham_msg_cloud, interpolation='bilinear')
plt.axis('off') # turn off axis
plt.show()

"""Below shows the spam message Wordcloud, it shows that maximum repeated words include ringtone,free,won etc."""

# wordcloud of spam messages
spam_msg_cloud = WordCloud(width =520, height =260, stopwords=STOPWORDS,max_font_size=50, background_color ="black", colormap='Blues').generate(spam_msg_text)
plt.figure(figsize=(16,10))
plt.imshow(spam_msg_cloud, interpolation='bilinear')
plt.axis('off') # turn off axis
plt.show()

plt.figure(figsize=(8,6))
sns.countplot(messages.label)
# Percentage of spam messages
(len(spam_msg)/len(ham_msg))*100 # 15.48%

"""Below, the bar chart shows that the classes are imbalanced.

There are several ways to handle the imbalance data, for instance

use of appropriate evaluation metrics

*   
resampling the training set : oversampling/upsampling or undersampling/downsampling
*   ensemble different resample datasets


  However, for our problem, we use downsampling just to illustrate how it is implemented.
"""

# one way to fix it is to downsample the ham msg
ham_msg_df = ham_msg.sample(n = len(spam_msg), random_state = 44)
spam_msg_df = spam_msg
print(ham_msg_df.shape, spam_msg_df.shape)

"""Below chart shows a similar distribution across message types after accounting for the imbalanced data."""

msg_df = pd.concat([ham_msg_df, spam_msg_df]).reset_index(drop=True)
plt.figure(figsize=(8, 6))
sns.countplot(data=msg_df, x='label')
plt.title('Distribution of ham and spam email messages (after downsampling)')

"""Furthermore, on average, the ham message has length of 73 words whereas spam message has 138.  """

# Add a new column for the length of each message
msg_df['text_length'] = msg_df['message'].apply(len)

# Group by 'label' and calculate the average text length for each label
labels = msg_df.groupby('label')['text_length'].mean()

print(labels)

"""Now we split the dataset into training(80%) and testing(20%) dataset

"""

# Map ham label as 0 and spam as 1
msg_df['msg_type']= msg_df['label'].map({'ham': 0, 'spam': 1})
msg_label = msg_df['msg_type'].values
# Split data into train and test
train_msg, test_msg, train_labels, test_labels = train_test_split(msg_df['message'], msg_label, test_size=0.2, random_state=434)

"""Tokenization

As deep learning models do not understand text, let’s convert text into numerical representation. For this purpose, a first step is Tokenization. The Tokenizer API from TensorFlow Keras splits sentences into words and encodes these into integers.

"""

# Defining pre-processing hyperparameters
max_len = 50
trunc_type = "post"
padding_type = "post"
oov_tok = "<OOV>"
vocab_size = 500

tokenizer = Tokenizer(num_words = vocab_size, char_level=False, oov_token = oov_tok)
tokenizer.fit_on_texts(train_msg)

"""Hyper-parameters used in Tokenizer object are: num_words and oov_token, char_level.

num_words: Indicate how many unique words to load in training and testing data. For our purpose, we selected 500 words (vocab_size)

oov_token: When its used, out of vocabulary token will be added to word index in the corpus which is used to build the model. This is used to replace out of vocabulary words (words that are not in our corpus) during text_to_sequence calls (see below).

char_level: If it is “True” then every character will be treated as a token. We set it as “False”, hence every word will be treated as a token.

We can get the word_index using tokenizer.word_index. A snapshot of word_index is printed below.
"""

# Get the word_index
word_index = tokenizer.word_index
word_index

# check how many words
tot_words = len(word_index)
print('There are %s unique tokens in training data. ' % tot_words)

"""Sequencing and Padding

After tokenization, we represent each sentence by sequences of numbers using texts_to_sequences() from tokenizer object. Subsequently, we use pad_sequences() so that each sequence will have same length. Sequencing and padding are done for both training and testing data.
"""

# Sequencing and padding on training and testing
training_sequences = tokenizer.texts_to_sequences(train_msg)
training_padded = pad_sequences (training_sequences, maxlen = max_len, padding = padding_type, truncating = trunc_type )
testing_sequences = tokenizer.texts_to_sequences(test_msg)
testing_padded = pad_sequences(testing_sequences, maxlen = max_len,
padding = padding_type, truncating = trunc_type)

"""padding = ‘pre’ or ‘post (default pre). By using pre, we pad before each sequence and by using post we pad after each sequence.

maxlen = maximum length of all sequences. Here max_len=50 hence, we are only going to use 50 words in a sentence. If not provided, by default it will use the maximum length of the longest sentence.

truncating = ‘pre’ or ‘post’ (default ‘pre’). If a sequence length is larger than the provided maxlen value then, these values will be truncated to maxlen. ‘pre’ option will truncate at the beginning where as ‘post’ will truncate at the end of the sequences.
"""

# Shape of train tensor
print('Shape of training tensor: ', training_padded.shape)
print('Shape of testing tensor: ', testing_padded.shape)

"""Before padding, first sequence is 27 word long where as second one is 24. Once the padding was applied, both sequences have length of 50."""

# Before padding
len(training_sequences[0]), len(training_sequences[1])

# After padding
len(training_padded[0]), len(training_padded[1])

"""As depicted below, the padded sequence has length of 50."""

print(training_padded[0])

"""Dense Spam Detection Model
With our data loaded and preprocessed, we’re now well prepared to use neural network architecture to classify the text message. Let’s train the model using a Dense architecture followed by LSTM and Bi-LSTM.

Define hyper-parameters:
"""

vocab_size = 500 # As defined earlier
embeding_dim = 16
drop_value = 0.2 # dropout
n_dense = 24

from keras.models import Sequential
from keras.layers import Embedding, GlobalAveragePooling1D, Dense, Dropout

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embeding_dim))
model.add(GlobalAveragePooling1D())
model.add(Dense(24, activation='relu'))
model.add(Dropout(drop_value))
model.add(Dense(1, activation='sigmoid'))

model.build(input_shape=(None, max_len))
print(model.summary())

"""Compiling the Dense model

Let’s compile our dense spam classifier model. We use ‘binary_crossentropy’ as a loss function because of binary output, ‘adam’ as an optimiser which makes use of momentum to avoid local minima and ‘accuracy’ as a measure of model performance.

binary_crossentropy: A loss function to optimize for binary classification.

adam:  optimizer for efficient weight updates.Adaptive learning rate for each weight.
Efficient and works well with large datasets and complex models.

accuracy: A metric to evaluate model performance during training and testing.
"""

model.compile(loss='binary_crossentropy',optimizer='adam' ,metrics=['accuracy'])

"""Training and evaluating the Dense model

Next, let’s fit our dense classifier using model.fit() argument. It uses padded training data and training labels for training the model and validation data for validating.


epoch: Number of times the learning algorithm will work through the entire training data set. We set it to be 20.


callbacks: callbacks is used to pass the early stopping parameter. EarlyStopping(monitor=’val_loss’, patience=2) is used to define that we want to monitor the validation loss and if the validation loss is not improved after two epochs, then the model training is stopped. It helps to avoid overfitting problem and indicates when to stop training before the learner begins over-fit. As depicted in the history results below, the validation loss is increased (i.e. not improved), continuously for 2 epochs (epoch 24: 0.12, and epoch 25: 0.13) after epoch 23, hence the model fitting has stopped at epoch 26.


verbose =2: lets to print loss and accuracy on each epoch
"""

# fitting a dense spam detector model
num_epochs = 30
early_stop = EarlyStopping(monitor='val_loss', patience=3)
history = model.fit(training_padded, train_labels, epochs=num_epochs, validation_data=(testing_padded, test_labels),callbacks =[early_stop], verbose=2)

"""The model resulted , training loss: 0.07, training accuracy: 97%, validation loss: 0.13 and validation accuracy: 94%."""

# Model performance on test data
model.evaluate(testing_padded, test_labels)

"""We can further visualize the history results by plotting loss and accuracy by number of epochs."""

# Read as a dataframe
metrics = pd.DataFrame(history.history)
# Rename column
metrics.rename(columns = {'loss': 'Training_Loss', 'accuracy': 'Training_Accuracy', 'val_loss': 'Validation_Loss', 'val_accuracy': 'Validation_Accuracy'}, inplace = True)
def plot_graphs1(var1, var2, string):
    metrics[[var1, var2]].plot()
    plt.title('Training and Validation ' + string)
    plt.xlabel ('Number of epochs')
    plt.ylabel(string)
    plt.legend([var1, var2])

plot_graphs1('Training_Loss', 'Validation_Loss', 'loss')

plot_graphs1('Training_Accuracy', 'Validation_Accuracy', 'accuracy')

"""Long Short Term Memory (LSTM) Model
Below, we fit the spam detection model using LSTM. Some new hyper-parameters used in LSTM below are n_lstm and return_sequences.

n_lstm = 20 is the number of nodes in the hidden layers within the LSTM cell
return_sequences=True ensures that the LSTM cell returns all of the outputs from the unrolled LSTM cell through time. If this argument is not used, the LSTM cell will simply provide the output of the LSTM cell from the previous step.

Below are hyper-parameters used for LSTM model.
"""

#LSTM hyperparameters
n_lstm = 20
drop_lstm =0.2

"""Let’s define LSTM spam detection model architecture. In Keras, by simply adding LSTM we can fit the LSTM model."""

from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense

# Define the model
model1 = Sequential()
model1.add(Embedding(input_dim=vocab_size, output_dim=embeding_dim))  # `input_length` removed
model1.add(LSTM(n_lstm, dropout=drop_lstm, return_sequences=True))  # First LSTM layer
model1.add(LSTM(n_lstm, dropout=drop_lstm))  # Second LSTM layer
model1.add(Dense(1, activation='sigmoid'))  # Output layer

# Build the model explicitly with input shape
model1.build(input_shape=(None, max_len))

# Print the summary
print(model1.summary())



model1.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

num_epochs = 30
early_stop = EarlyStopping(monitor='val_loss', patience=5)
history = model1.fit(training_padded, train_labels, epochs=num_epochs, validation_data=(testing_padded, test_labels),callbacks =[early_stop], verbose=2)

# Model performance on test data
model1.evaluate(testing_padded, test_labels)

# Create a dataframe
metrics = pd.DataFrame(history.history)
# Rename column
metrics.rename(columns = {'loss': 'Training_Loss', 'accuracy': 'Training_Accuracy',
                         'val_loss': 'Validation_Loss', 'val_accuracy': 'Validation_Accuracy'}, inplace = True)
def plot_graphs1(var1, var2, string):
    metrics[[var1, var2]].plot()
    plt.title('LSTM Model: Training and Validation ' + string)
    plt.xlabel ('Number of epochs')
    plt.ylabel(string)
    plt.legend([var1, var2])
plot_graphs1('Training_Loss', 'Validation_Loss', 'loss')
plot_graphs1('Training_Accuracy', 'Validation_Accuracy', 'accuracy')

"""Bi-directional Long Short Term Memory (BiLSTM) Model
Unlike in LSTM, the Bi-LSTM learns patterns from both before and after a given token within a document. The Bi-LSTM back-propagates in both backward and forward directions in time. Due to this, the computational time is increased compared to LSTM. However, in most of the cases Bi-LSTM results in better accuracy.

Below, we can see the Bi-directional LSTM architecture, where only difference than LSTM is that we use Bidirectional wrapper to LSTM.
"""

# Biderectional LSTM Spam detection architecture
model2 = Sequential()
model2.add(Embedding(vocab_size, embeding_dim, input_length=max_len))
model2.add(Bidirectional(LSTM(n_lstm, dropout=drop_lstm, return_sequences=True)))
model2.add(Dense(1, activation='sigmoid'))

from keras.models import Sequential
from keras.layers import Embedding, LSTM, Bidirectional, Dense

# Define the Bidirectional LSTM model
model2 = Sequential()
model2.add(Embedding(input_dim=vocab_size, output_dim=embeding_dim))  # `input_length` removed
model2.add(Bidirectional(LSTM(n_lstm, dropout=drop_lstm, return_sequences=True)))  # Bidirectional LSTM layer
model2.add(Dense(1, activation='sigmoid'))  # Output layer

# Explicitly build the model
model2.build(input_shape=(None, max_len))

# Print the summary
print(model2.summary())

"""Compiling"""

model2.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

"""Training and evaluation BiLSTM model"""

from keras.models import Sequential
from keras.layers import Embedding, LSTM, Bidirectional, Dense

# Corrected Bidirectional LSTM model
model2 = Sequential()
model2.add(Embedding(input_dim=vocab_size, output_dim=embeding_dim))  # Embedding layer
model2.add(Bidirectional(LSTM(n_lstm, dropout=drop_lstm)))  # Remove `return_sequences`
model2.add(Dense(1, activation='sigmoid'))  # Output layer

# Build the model
model2.build(input_shape=(None, max_len))

# Print the summary
print(model2.summary())

from keras.callbacks import EarlyStopping

# Compile the model
model2.compile(
    optimizer='adam',  # Optimizer
    loss='binary_crossentropy',  # Loss function for binary classification
    metrics=['accuracy']  # Metrics to monitor
)

# Define EarlyStopping
early_stop = EarlyStopping(monitor='val_loss', patience=5)

# Train the model
history = model2.fit(
    training_padded,  # Input data
    train_labels,     # Target labels
    epochs=50,        # Number of epochs
    validation_data=(testing_padded, test_labels),  # Validation data
    callbacks=[early_stop],  # Callbacks
    verbose=4         # Verbosity level
)

# Model performance on test data
model2.evaluate(testing_padded, test_labels)

# Create a dataframe
metrics = pd.DataFrame(history.history)
# Rename column
metrics.rename(columns = {'loss': 'Training_Loss', 'accuracy': 'Training_Accuracy',
                         'val_loss': 'Validation_Loss', 'val_accuracy': 'Validation_Accuracy'}, inplace = True)
def plot_graphs1(var1, var2, string):
    metrics[[var1, var2]].plot()
    plt.title('BiLSTM Model: Training and Validation ' + string)
    plt.xlabel ('Number of epochs')
    plt.ylabel(string)
    plt.legend([var1, var2])
# Plot
plot_graphs1('Training_Loss', 'Validation_Loss', 'loss')
plot_graphs1('Training_Accuracy', 'Validation_Accuracy', 'accuracy')

"""**Compare three different models and select a final one**

All Dense, LSTM and Bi-LSTM models are comparable in terms of loss and accuracy. The validation loss for these three models are 0.13, 0.31 and 0.18, respectively. And, the validation accuracy are 94%, 91% and 95%, respectively.

Among all, both Dense and BiLSTM outperformed the LSTM. Based on loss, accuracy and the plots above, we select Dense architecture as a final model for classifying the text messages for spam or ham. The dense classifier has simple structure and the loss and accuracy over epochs are more stable than in BiLSTM.
"""

# Comparing three different models
print(f"Dense architecture loss and accuracy: {model.evaluate(testing_padded, test_labels)} " )
print(f"LSTM architecture loss and accuracy: {model1.evaluate(testing_padded, test_labels)} " )
print(f"Bi-LSTM architecture loss and accuracy: {model2.evaluate(testing_padded, test_labels)} " )

"""**Predict spam/ham on new messages**

Scenario 1: Using raw text from our data:

Let’s evaluate how our Dense spam detection model predicts/classifies whether its spam or ham given the text from our original data. First and second messages below are ham whereas the third one is a spam message. We’ve used the same tokenizer that we created earlier in the code to convert them into the sequences. This makes sure the new words will have the same token as in the training set. Once tokenized, we use padding as we did earlier and provide the same dimension as in training set.
"""

# display long string
pd.options.display.max_colwidth=150
messages[:10]

predict_msg = ["Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",
          "Ok lar... Joking wif u oni...",
          "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"]

# Defining prediction function
def predict_spam(predict_msg):
    new_seq = tokenizer.texts_to_sequences(predict_msg)
    padded = pad_sequences(new_seq, maxlen =max_len,
                      padding = padding_type,
                      truncating=trunc_type)
    return (model.predict(padded))
predict_spam(predict_msg)

"""As shown b, above model correctly predicts first two sentences as not spam where as the third one as spam. There is 99% chance that the third sentence is spam."""



"""Scenario 2:

Using newly created text message and see how the model classifies them.
"""

# The third one gives 0.99 indicating very high probabilty of spam
predict_msg = ["You are awarded a Nikon Digital Camera. Call now",
               "Call me",
          "What's up?",
               "wassupp buddy",
               "Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with",
               "INNER!! As a valued network customer you have been selected to receivea £900 prize reward!"]
predict_spam(predict_msg)

import numpy as np

# Example output from the predict_spam function
predict_msg = ["You are awarded a Nikon Digital Camera. Call now",
               "Call me",
               "What's up?",
               "wassupp",
               "Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with",
               "INNER!! As a valued network customer you have been selected to receivea £900 prize reward! "]

# Ensure output_probabilities is defined
output_probabilities = np.array([[0.940969], [0.07317297], [0.02140625]], dtype=np.float32)

# Convert to percentages and round to 2 decimal places
output_percentages = np.around(output_probabilities * 100, decimals=2)

# Display the message and corresponding spam probability
for msg, percentage in zip(predict_msg, output_percentages):
    print(f"Message: '{msg}' - Spam Probability: {percentage[0]}%")

import ipywidgets as widgets
from IPython.display import display
import numpy as np


# Define the prediction function (ensure the model and tokenizer are loaded)
def predict_spam(predict_msg):
    new_seq = tokenizer.texts_to_sequences(predict_msg)
    padded = pad_sequences(new_seq, maxlen=max_len, padding=padding_type, truncating=trunc_type)
    return model.predict(padded)

# Create a text box for message input
message_input = widgets.Text(
    description='Message:',
    placeholder='Enter your message here',
    style={'description_width': 'initial'}
)

# Create a button for spam detection
button = widgets.Button(description="Check Spam")

# Function to display spam prediction when button is clicked
def on_button_click(b):
    message = message_input.value
    if message.strip() == "":  # Handle empty input
        print("Please enter a message.")
        return

    # Get the prediction
    output_probabilities = predict_spam([message])
    output_percentages = np.around(output_probabilities * 100, decimals=2)

    # Display the result
    print(f"Message: '{message}'\nSpam Probability: {output_percentages[0][0]}%")

# Link the button click event to the function
button.on_click(on_button_click)

# Display the input field and button
display(message_input, button)

from sklearn.metrics import accuracy_score, precision_score, recall_score

# Get predictions for test data using the trained model
predictions = model2.predict(testing_padded)

# Convert probabilities to binary labels (threshold 0.5)
predictions = (predictions > 0.5).astype(int)

# Calculate accuracy
accuracy = accuracy_score(test_labels, predictions)

# Calculate precision
precision = precision_score(test_labels, predictions)

# Calculate recall
recall = recall_score(test_labels, predictions)

# Print the metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")

"""**BAR CHART FOR ACCURACY PRECISION RECALL**"""

import matplotlib.pyplot as plt

# Metrics for visualization
metrics = {'Accuracy': accuracy, 'Precision': precision, 'Recall': recall}

# Create a bar plot
plt.figure(figsize=(8, 6))
plt.bar(metrics.keys(), metrics.values(), color=['blue', 'orange', 'green'])

# Adding title and labels
plt.title('Model Performance: Accuracy, Precision, and Recall')
plt.ylabel('Score')
plt.ylim(0, 1)

# Show the plot
plt.show()

"""**CONFUSION MATRIX**(to understand the misclassifications.)"""

from sklearn.metrics import confusion_matrix
import seaborn as sns

# Compute confusion matrix
cm = confusion_matrix(test_labels, predictions)

# Plot the confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Ham', 'Spam'], yticklabels=['Ham', 'Spam'])
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

"""**PRECISION RECALL CURVE**(to analyze the balance between precision and recall.)"""

from sklearn.metrics import precision_recall_curve
import matplotlib.pyplot as plt

# Compute precision and recall for different thresholds
precision, recall, _ = precision_recall_curve(test_labels, predictions)

# Plot precision-recall curve
plt.figure(figsize=(8, 6))
plt.plot(recall, precision, color='b', label='Precision-Recall Curve')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.legend()
plt.show()

"""**ROC CURVE**(for understanding model performance in classification tasks.)"""

from sklearn.metrics import roc_curve

# Compute ROC curve
fpr, tpr, _ = roc_curve(test_labels, predictions)

# Plot ROC curve
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='b', label='ROC Curve')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')  # diagonal line
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend()
plt.show()



!pip install python-telegram-bot nest_asyncio



import nest_asyncio
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes

# Allow nested event loops in Colab
nest_asyncio.apply()

# Replace with your bot token
TELEGRAM_TOKEN = '7554149148:AAHc7f9_xv1nmSR7XIvKxRcsCSjGH0X0h90'

# Define the start command
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Welcome! Send me a message, and I'll tell you its spam probability.")

# Define the message handler
async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_message = update.message.text
    # Assuming 'predict_spam' is a function that returns the probability of the message being spam
    spam_probability = predict_spam([user_message])[0][0]  # Get the spam probability
    response = f"Message: '{user_message}'\nSpam Probability: {spam_probability * 100:.0f}%"
    await update.message.reply_text(response)

# Set up the bot application
def main():
    application = Application.builder().token(TELEGRAM_TOKEN).build()

    # Add handlers
    application.add_handler(CommandHandler("start", start))
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    return application

# Run the bot in Colab
application = main()

async def run_bot():
    # Initialize the application
    await application.initialize()
    print("Bot initialized...")

    # Start receiving updates
    await application.start()
    print("Bot is running...")

    # Keep the bot running indefinitely (or until interrupted)
    await application.updater.start_polling()

# Run the bot in Colab's event loop
await run_bot()